apiVersion: v1
kind: Config
clusters:
- cluster:
    server: https://123.456.78.90:6443  # Replace with your Kubernetes API server URL
    certificate-authority-data: LS0tLS1CRUdJTiB...  # Base64-encoded CA certificate
  name: my-cluster
contexts:
- context:
    cluster: my-cluster
    user: my-user
  name: my-context
current-context: my-context
users:
- name: my-user
  user:
    token: "${{ secrets.KUBE_CONFIG }}"  # Placeholder for your token or password
