apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: weather-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-be
  template:
    metadata:
      labels:
        app: weather-be
    spec:
      containers:
        - name: weather-be
          image: sekharatulsingh2016/weather-be
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: weather-app
spec:
  selector:
    app: weather-be
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
