apiVersion: v1
kind: Service
metadata:
  name: weather-frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: weather-frontend

---
apiVersion: v1
kind: Service
metadata:
  name: weather-backend
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: weather-backend
