name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the Docker image for backend
        run: docker build . --file ../../weather-be/Dockerfile --tag weather-backend:$(date +%s)

      - name: Build the Docker image for frontend
        run: docker build . --file ../../weather-fe/Dockerfile --tag weather-frontend:$(date +%s)
