name: Build and Run Docker Container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t weather-froentend .
          
      - name: Run Docker container
        run: |
          docker run -p 3001:3001 weather-frontend

      - name: Build Docker image
        run: |
          docker build -t weather-backend .
          
      - name: Run Docker container
        run: |
          docker run -p 3000:3000 weather-backend
