name: Run Python Script

on:
  push:
    branches:
      - main  # Trigger when changes are pushed to the main branch
  workflow_dispatch:

jobs:
  run_python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies (if needed)
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run Python Script
        run: python ../../weather.py
