name: Run JavaScript File

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run JavaScript File in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app node:16-alpine sh -c "npm install && node weather.js"
